blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/acominotto/focus-tower/discussions
    about: Ask questions or share ideas that aren't bugs or feature requests
